### ISSUE TITLE
Modules with no current version on puppetforge fail with stacktrace

### ISSUE THREAD

**Issue by indero** [vshn/crmngr#13]
I noticed the problem with following module:
https://forge.puppet.com/ripienaar/module_data
This module was deleted some time ago.

The [puppetforge API](https://forgeapi.puppetlabs.com/v3/modules/ripienaar-module_data) states that this module has no current release.
```
"current_release": null,
```

crmngr fails with a stacktrace
```
Traceback (most recent call last):
  File "/usr/local/bin/crmngr", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/crmngr/__init__.py", line 67, in main
    version_cache=version_cache)
  File "/usr/local/lib/python3.5/dist-packages/crmngr/__init__.py", line 158, in command_report
    wrap=cli_args.wrap,
  File "/usr/local/lib/python3.5/dist-packages/crmngr/controlrepository.py", line 660, in report
    version_cache
  File "/usr/local/lib/python3.5/dist-packages/crmngr/puppetfile.py", line 316, in print_version_information
    latest_version = self.get_latest_version(version_cache)
  File "/usr/local/lib/python3.5/dist-packages/crmngr/puppetfile.py", line 347, in get_latest_version
    author=self.author
  File "/usr/local/lib/python3.5/dist-packages/crmngr/forgeapi.py", line 48, in current_version
    'version': api_info['version'],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by andrekeller** [comment]
Fixed in 1fc8e5a397f6496fed1bd0bbaa62727b0aa39c8d
